name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  # riverpod: ^2.5.0
  
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  cloud_firestore: ^4.15.4
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/time-tracking.svg

